# make sure to change config name to compare_config.yml and store in the same
# directory as the .py script
# configuration is simple : separated name of parameter : value of parameter
# note that there are no spaces between the :
# input one and two indicates the files you want to compare

input_one:some/file/path.txt
input_two:some/file/path.txt

# start dirs are the directories within the files you want to look at
# all preceding directories will be ignored

start_dir_one:/a/starting/directory
start_dir_two:/a/starting/directory

# report entries designate the two reports, full match and candidate matches

match_report:match_report.txt

# certainty percentage is percentage difference between file characteristics
# that would mark something as a candidate
# 100 would be 100% certain, where as 96 would be 96% certain

certainty_offset:96
